services:
  app:
    build: .
    container_name: hyperpure-app
    ports:
      - "8081:19006"  # Updated internal port from 19006 to 8081 for modern Expo Web
    volumes:
      - .:/app
      - /app/node_modules # <-- This anonymous volume protects the container's node_modules

    environment:
      - NODE_ENV=production #<-- Change this to production in production or development to work in local -->
      - EXPO_WEBPACK_ALLOWED_HOSTS=all
    command: npm run web:dev



  hyperpure-api:
    build: ../hyperpure_api_server
    container_name: hyperpure-api
    ports:
      - "5000:5000"
    # Add this line to automatically load the variables:
    env_file:
      - ../hyperpure_api_server/.env
    volumes:
      - /home/arul/hyperpure_marketplace:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=production
    command: node server.js

   

